// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: pkg/replica/rpc/weftsnap/weftsnap.proto

package weftsnap

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Range is one contiguous (offset, size) byte window.
type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_pkg_replica_rpc_weftsnap_weftsnap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_replica_rpc_weftsnap_weftsnap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDescGZIP(), []int{0}
}

func (x *Range) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Range) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SnapshotName is the engine-side name (e.g. the registry UUID).
	SnapshotName string `protobuf:"bytes,1,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	// VolumeName matches what the replica was opened with (BackupStatus
	// assertOpen check needs it).
	VolumeName string `protobuf:"bytes,2,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	// ChunkSize : server-emitted chunk size in bytes. 0 → server default
	// (4 MiB). Tunable so very-high-latency clients can ask for bigger
	// chunks to amortise grpc framing.
	ChunkSize int64 `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	// Ranges, when non-empty, restricts the stream to the given byte
	// windows (in order, no de-duplication). Empty = full stream.
	Ranges        []*Range `protobuf:"bytes,4,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_pkg_replica_rpc_weftsnap_weftsnap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_replica_rpc_weftsnap_weftsnap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDescGZIP(), []int{1}
}

func (x *ReadRequest) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

func (x *ReadRequest) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *ReadRequest) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *ReadRequest) GetRanges() []*Range {
	if x != nil {
		return x.Ranges
	}
	return nil
}

type ReadChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offset is the byte offset of this chunk's first byte within the
	// snapshot. Always monotonically increasing across the stream.
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Data is the chunk's payload. Length is ≤ chunk_size ; the final
	// chunk of a range may be smaller when range_size % chunk_size != 0.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Last is true ONLY on the final chunk of the whole stream.
	Last          bool `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunk) Reset() {
	*x = ReadChunk{}
	mi := &file_pkg_replica_rpc_weftsnap_weftsnap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunk) ProtoMessage() {}

func (x *ReadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_replica_rpc_weftsnap_weftsnap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunk.ProtoReflect.Descriptor instead.
func (*ReadChunk) Descriptor() ([]byte, []int) {
	return file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDescGZIP(), []int{2}
}

func (x *ReadChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

type CompareRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SnapshotName is the newer snapshot (the one we'd back up from).
	SnapshotName string `protobuf:"bytes,1,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	// ParentSnapshotName is the older one (which the client already has
	// a backup of). Empty parent = "compare against nothing" = full.
	ParentSnapshotName string `protobuf:"bytes,2,opt,name=parent_snapshot_name,json=parentSnapshotName,proto3" json:"parent_snapshot_name,omitempty"`
	VolumeName         string `protobuf:"bytes,3,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	// BlockSize is the granularity the compare walker emits ranges at.
	// 0 → server default. Practical values : 1 MiB to 16 MiB.
	BlockSize     int64 `protobuf:"varint,4,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareRequest) Reset() {
	*x = CompareRequest{}
	mi := &file_pkg_replica_rpc_weftsnap_weftsnap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareRequest) ProtoMessage() {}

func (x *CompareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_replica_rpc_weftsnap_weftsnap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareRequest.ProtoReflect.Descriptor instead.
func (*CompareRequest) Descriptor() ([]byte, []int) {
	return file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDescGZIP(), []int{3}
}

func (x *CompareRequest) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

func (x *CompareRequest) GetParentSnapshotName() string {
	if x != nil {
		return x.ParentSnapshotName
	}
	return ""
}

func (x *CompareRequest) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *CompareRequest) GetBlockSize() int64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type CompareResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BlockSize echoes the effective compare granularity.
	BlockSize int64 `protobuf:"varint,1,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	// Ranges are the byte windows where SnapshotName differs from
	// ParentSnapshotName. Empty list = identical snapshots.
	Ranges        []*Range `protobuf:"bytes,2,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareResponse) Reset() {
	*x = CompareResponse{}
	mi := &file_pkg_replica_rpc_weftsnap_weftsnap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareResponse) ProtoMessage() {}

func (x *CompareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_replica_rpc_weftsnap_weftsnap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareResponse.ProtoReflect.Descriptor instead.
func (*CompareResponse) Descriptor() ([]byte, []int) {
	return file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDescGZIP(), []int{4}
}

func (x *CompareResponse) GetBlockSize() int64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *CompareResponse) GetRanges() []*Range {
	if x != nil {
		return x.Ranges
	}
	return nil
}

var File_pkg_replica_rpc_weftsnap_weftsnap_proto protoreflect.FileDescriptor

const file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDesc = "" +
	"\n" +
	"'pkg/replica/rpc/weftsnap/weftsnap.proto\x12\x15weftblock.replicasnap\"3\n" +
	"\x05Range\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"\xa8\x01\n" +
	"\vReadRequest\x12#\n" +
	"\rsnapshot_name\x18\x01 \x01(\tR\fsnapshotName\x12\x1f\n" +
	"\vvolume_name\x18\x02 \x01(\tR\n" +
	"volumeName\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x03R\tchunkSize\x124\n" +
	"\x06ranges\x18\x04 \x03(\v2\x1c.weftblock.replicasnap.RangeR\x06ranges\"K\n" +
	"\tReadChunk\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\"\xa7\x01\n" +
	"\x0eCompareRequest\x12#\n" +
	"\rsnapshot_name\x18\x01 \x01(\tR\fsnapshotName\x120\n" +
	"\x14parent_snapshot_name\x18\x02 \x01(\tR\x12parentSnapshotName\x12\x1f\n" +
	"\vvolume_name\x18\x03 \x01(\tR\n" +
	"volumeName\x12\x1d\n" +
	"\n" +
	"block_size\x18\x04 \x01(\x03R\tblockSize\"f\n" +
	"\x0fCompareResponse\x12\x1d\n" +
	"\n" +
	"block_size\x18\x01 \x01(\x03R\tblockSize\x124\n" +
	"\x06ranges\x18\x02 \x03(\v2\x1c.weftblock.replicasnap.RangeR\x06ranges2\xba\x01\n" +
	"\x0eSnapshotReader\x12N\n" +
	"\x04Read\x12\".weftblock.replicasnap.ReadRequest\x1a .weftblock.replicasnap.ReadChunk0\x01\x12X\n" +
	"\aCompare\x12%.weftblock.replicasnap.CompareRequest\x1a&.weftblock.replicasnap.CompareResponseB9Z7github.com/openweft/weft-block/pkg/replica/rpc/weftsnapb\x06proto3"

var (
	file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDescOnce sync.Once
	file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDescData []byte
)

func file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDescGZIP() []byte {
	file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDescOnce.Do(func() {
		file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDesc), len(file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDesc)))
	})
	return file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDescData
}

var file_pkg_replica_rpc_weftsnap_weftsnap_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_replica_rpc_weftsnap_weftsnap_proto_goTypes = []any{
	(*Range)(nil),           // 0: weftblock.replicasnap.Range
	(*ReadRequest)(nil),     // 1: weftblock.replicasnap.ReadRequest
	(*ReadChunk)(nil),       // 2: weftblock.replicasnap.ReadChunk
	(*CompareRequest)(nil),  // 3: weftblock.replicasnap.CompareRequest
	(*CompareResponse)(nil), // 4: weftblock.replicasnap.CompareResponse
}
var file_pkg_replica_rpc_weftsnap_weftsnap_proto_depIdxs = []int32{
	0, // 0: weftblock.replicasnap.ReadRequest.ranges:type_name -> weftblock.replicasnap.Range
	0, // 1: weftblock.replicasnap.CompareResponse.ranges:type_name -> weftblock.replicasnap.Range
	1, // 2: weftblock.replicasnap.SnapshotReader.Read:input_type -> weftblock.replicasnap.ReadRequest
	3, // 3: weftblock.replicasnap.SnapshotReader.Compare:input_type -> weftblock.replicasnap.CompareRequest
	2, // 4: weftblock.replicasnap.SnapshotReader.Read:output_type -> weftblock.replicasnap.ReadChunk
	4, // 5: weftblock.replicasnap.SnapshotReader.Compare:output_type -> weftblock.replicasnap.CompareResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_replica_rpc_weftsnap_weftsnap_proto_init() }
func file_pkg_replica_rpc_weftsnap_weftsnap_proto_init() {
	if File_pkg_replica_rpc_weftsnap_weftsnap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDesc), len(file_pkg_replica_rpc_weftsnap_weftsnap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_replica_rpc_weftsnap_weftsnap_proto_goTypes,
		DependencyIndexes: file_pkg_replica_rpc_weftsnap_weftsnap_proto_depIdxs,
		MessageInfos:      file_pkg_replica_rpc_weftsnap_weftsnap_proto_msgTypes,
	}.Build()
	File_pkg_replica_rpc_weftsnap_weftsnap_proto = out.File
	file_pkg_replica_rpc_weftsnap_weftsnap_proto_goTypes = nil
	file_pkg_replica_rpc_weftsnap_weftsnap_proto_depIdxs = nil
}
