// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: pkg/replica/rpc/weftsnap/weftsnap.proto

package weftsnap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnapshotReader_Read_FullMethodName    = "/weftblock.replicasnap.SnapshotReader/Read"
	SnapshotReader_Compare_FullMethodName = "/weftblock.replicasnap.SnapshotReader/Compare"
)

// SnapshotReaderClient is the client API for SnapshotReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SnapshotReader streams a snapshot's frozen contents from a replica. The
// server opens the snapshot at the start of the stream (read-only, doesn't
// touch the chain) and closes it when the stream ends (natural completion
// OR client cancel).
type SnapshotReaderClient interface {
	// Read streams the snapshot's bytes. Empty `ranges` → full stream from
	// offset 0 to snapshot size. Non-empty `ranges` → sparse stream
	// covering only the requested (offset, size) windows in the listed
	// order — used by the incremental backup path after Compare reports
	// which blocks differ from the parent.
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadChunk], error)
	// Compare returns the (offset, size) byte windows that differ between
	// snapshot_name and parent_snapshot_name. Backed by upstream Longhorn
	// BackupStatus.CompareSnapshot which walks the replica's sector
	// location table — much cheaper than a SHA-256-per-block sweep.
	// Returns Unimplemented when the server's compare path isn't wired
	// (the driver-side falls back to a full backup with a logged note).
	Compare(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*CompareResponse, error)
}

type snapshotReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotReaderClient(cc grpc.ClientConnInterface) SnapshotReaderClient {
	return &snapshotReaderClient{cc}
}

func (c *snapshotReaderClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SnapshotReader_ServiceDesc.Streams[0], SnapshotReader_Read_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadRequest, ReadChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnapshotReader_ReadClient = grpc.ServerStreamingClient[ReadChunk]

func (c *snapshotReaderClient) Compare(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*CompareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareResponse)
	err := c.cc.Invoke(ctx, SnapshotReader_Compare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotReaderServer is the server API for SnapshotReader service.
// All implementations must embed UnimplementedSnapshotReaderServer
// for forward compatibility.
//
// SnapshotReader streams a snapshot's frozen contents from a replica. The
// server opens the snapshot at the start of the stream (read-only, doesn't
// touch the chain) and closes it when the stream ends (natural completion
// OR client cancel).
type SnapshotReaderServer interface {
	// Read streams the snapshot's bytes. Empty `ranges` → full stream from
	// offset 0 to snapshot size. Non-empty `ranges` → sparse stream
	// covering only the requested (offset, size) windows in the listed
	// order — used by the incremental backup path after Compare reports
	// which blocks differ from the parent.
	Read(*ReadRequest, grpc.ServerStreamingServer[ReadChunk]) error
	// Compare returns the (offset, size) byte windows that differ between
	// snapshot_name and parent_snapshot_name. Backed by upstream Longhorn
	// BackupStatus.CompareSnapshot which walks the replica's sector
	// location table — much cheaper than a SHA-256-per-block sweep.
	// Returns Unimplemented when the server's compare path isn't wired
	// (the driver-side falls back to a full backup with a logged note).
	Compare(context.Context, *CompareRequest) (*CompareResponse, error)
	mustEmbedUnimplementedSnapshotReaderServer()
}

// UnimplementedSnapshotReaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotReaderServer struct{}

func (UnimplementedSnapshotReaderServer) Read(*ReadRequest, grpc.ServerStreamingServer[ReadChunk]) error {
	return status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedSnapshotReaderServer) Compare(context.Context, *CompareRequest) (*CompareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compare not implemented")
}
func (UnimplementedSnapshotReaderServer) mustEmbedUnimplementedSnapshotReaderServer() {}
func (UnimplementedSnapshotReaderServer) testEmbeddedByValue()                        {}

// UnsafeSnapshotReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotReaderServer will
// result in compilation errors.
type UnsafeSnapshotReaderServer interface {
	mustEmbedUnimplementedSnapshotReaderServer()
}

func RegisterSnapshotReaderServer(s grpc.ServiceRegistrar, srv SnapshotReaderServer) {
	// If the following call panics, it indicates UnimplementedSnapshotReaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotReader_ServiceDesc, srv)
}

func _SnapshotReader_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SnapshotReaderServer).Read(m, &grpc.GenericServerStream[ReadRequest, ReadChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnapshotReader_ReadServer = grpc.ServerStreamingServer[ReadChunk]

func _SnapshotReader_Compare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotReaderServer).Compare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotReader_Compare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotReaderServer).Compare(ctx, req.(*CompareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotReader_ServiceDesc is the grpc.ServiceDesc for SnapshotReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weftblock.replicasnap.SnapshotReader",
	HandlerType: (*SnapshotReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compare",
			Handler:    _SnapshotReader_Compare_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Read",
			Handler:       _SnapshotReader_Read_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/replica/rpc/weftsnap/weftsnap.proto",
}
